" Environment
set directory=$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

syntax on
filetype plugin indent on

set autoindent
set backspace=indent,eol,start
set complete-=1
set expandtab
set laststatus=0
set nrformats-=octal
set number
set ruler
set cc=80
set scrolloff=1
set sessionoptions-=options
set shiftwidth=2
set showcmd
set sidescrolloff=5
set smarttab
set softtabstop=2
set tabstop=2
set wildmenu

set display+=lastline
set encoding=utf-8

nnoremap K i<CR><Esc>

autocmd FileType make set noexpandtab
