#!/bin/zsh

alias ..='cd ..'
alias ls='ls --color=auto'
alias s='sudo su -'
alias vi='vim'

if [[ -x "$(command -v tmux)" ]] ; then
  alias t='TMUX= tmux'
  alias ta='TMUX= tmux attach -t'
  alias tn='tmux new -s'
fi

if [[ -x "$(command -v xstow)" ]] ; then
  alias stow='xstow'
fi
