#!/bin/zsh

# make a directory and cd into it
function mcd() {
  mkdir -p "$1" && cd "$1"
}

# basically an alias for git, except we automatically get a git status if no
# arguments are passed
if [[ -x "$(command -v git)" ]] ; then
  function g() {
    if [[ $# -gt 0 ]] ; then
      git "$@"
    else
      git status
    fi
  }
fi
